name: project_2
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flame: 1.20.0
  get: 4.6.6
  flame_forge2d: 0.18.2+1
  hive_ce: 2.5.0+2
  hive_ce_flutter: 2.0.0
  google_fonts:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
